#############################################################################
# Makefile for building: compressor
# Generated by qmake (2.01a) (Qt 4.8.6) on: Mon Dec 8 08:37:54 2014
# Project:  compressor.pro
# Template: app
# Command: /usr/lib/x86_64-linux-gnu/qt4/bin/qmake -o Makefile compressor.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = 
CFLAGS        = -m64 -pipe -O2 -Wall
CXXFLAGS      = -m64 -pipe -O2 -Wall
INCPATH       = -Iinc -I$(shell lhapdf-config --incdir) -I$(shell root-config --incdir)
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
LIBS          = $(shell lhapdf-config --libs) $(shell gsl-config --libs) $(shell root-config --glibs)
AR            = ar cqs
RANLIB        = 
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = obj/

####### Files

SOURCES       = src/main.cc \
		src/utils.cc \
		src/Minimizer.cc \
		src/Estimators.cc \
		src/Grid.cc 
OBJECTS       = obj/main.o \
		obj/utils.o \
		obj/Minimizer.o \
		obj/Estimators.o \
		obj/Grid.o
DESTDIR       = 
TARGET        = compressor

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

clean: 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 

####### Compile

obj/main.o: src/main.cc 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/main.o src/main.cc

obj/utils.o: src/utils.cc 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/utils.o src/utils.cc

obj/Minimizer.o: src/Minimizer.cc 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/Minimizer.o src/Minimizer.cc

obj/Estimators.o: src/Estimators.cc 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/Estimators.o src/Estimators.cc

obj/Grid.o: src/Grid.cc 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/Grid.o src/Grid.cc

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

