#############################################################################
# Makefile for building: compressor
# Generated by qmake (2.01a) (Qt 4.8.6) on: Fri Sep 26 13:37:40 2014
# Project:  compressor.pro
# Template: app
# Command: /usr/lib/x86_64-linux-gnu/qt4/bin/qmake -o Makefile compressor.pro
#############################################################################

####### Compiler, tools and options
CC            = icc
CXX           = icpc
DEFINES       = 
CFLAGS        = -m64 -pipe -O3 -Wall -W $(DEFINES) 
CXXFLAGS      = -m64 -pipe -O3 -Wall -W $(DEFINES)
INCPATH       = -I./inc/ -I/opt/lhapdf6/include $(shell gsl-config --cflags)
LINK          = icpc
LFLAGS        = -m64 -Wl,-O1
LIBS          = $(SUBLIBS) -L/opt/lhapdf6/lib -lLHAPDF $(shell gsl-config --libs)
AR            = ar cqs
RANLIB        = 
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = obj/

####### Files

SOURCES       = src/randomgenerator.cc \
	        src/main.cc \
	        src/mini.cc
OBJECTS       = obj/randomgenerator.o \
	        obj/main.o \
		obj/mini.o
DESTDIR       = 
TARGET        = compressor

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

clean: 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 

check: first

####### Compile
obj/main.o:  src/main.cc 
	$(CXX) -c $(CXXFLAGS) $(GSLINCLUDE) $(INCPATH) -o obj/main.o src/main.cc

####### Compile
obj/mini.o:  src/mini.cc 
	$(CXX) -c $(CXXFLAGS) $(GSLINCLUDE) $(INCPATH) -o obj/mini.o src/mini.cc

obj/randomgenerator.o: src/randomgenerator.cc
	$(CXX) -c $(CXXFLAGS) $(GSLINCLUDE) $(INCPATH) -o obj/randomgenerator.o src/randomgenerator.cc

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

